// <auto-generated />
using System;
using GroceriesDelivery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroceriesDelivery.Migrations
{
    [DbContext(typeof(GroceriesDeliveryContext))]
    [Migration("20210127023825_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GroceriesDelivery.Models.Customer", b =>
                {
                    b.Property<string>("CustID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("GroceriesDelivery.Models.Driver", b =>
                {
                    b.Property<string>("DriverID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DriverID");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("GroceriesDelivery.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCustID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerCustID");

                    b.HasIndex("DriverID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("GroceriesDelivery.Models.Order", b =>
                {
                    b.HasOne("GroceriesDelivery.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerCustID");

                    b.HasOne("GroceriesDelivery.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID");

                    b.Navigation("Customer");

                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
